import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  careSurveyResponses: defineTable({
    locale: v.string(),
    hasManagedCare: v.optional(v.string()),
    careTarget: v.optional(v.string()),
    caredPersonAge: v.optional(v.string()),
    familyCaregivers: v.optional(v.string()),
    coordinationFrequency: v.optional(v.string()),
    organizationMethod: v.string(),
    organizationOther: v.string(),
    organizationAppName: v.optional(v.string()),
    careChallenges: v.array(v.string()),
    careChallengesOther: v.string(),
    priorCareAppUse: v.optional(v.string()),
    priorCareAppName: v.optional(v.string()),
    hadIncident: v.string(),
    incidentStory: v.string(),
    currentlyPaysCare: v.optional(v.string()),
    paidCareDetails: v.optional(v.string()),
    carePayer: v.optional(v.string()),
    appTrust: v.string(),
    trustConcerns: v.array(v.string()),
    trustConcernsOther: v.string(),
    appInterest: v.string(),
    interestNoReason: v.string(),
    interestRequirements: v.optional(v.array(v.string())),
    interestRequirementOther: v.optional(v.string()),
    whatsappPreference: v.optional(v.string()),
    essentialFeatures: v.array(v.string()),
    essentialFeaturesOther: v.string(),
    discoveryChannel: v.optional(v.string()),
    discoveryOther: v.optional(v.string()),
    conditionDuration: v.optional(v.string()),
    priceTooExpensiveCents: v.union(v.number(), v.null()),
    priceExpensiveButPayCents: v.union(v.number(), v.null()),
    priceBargainCents: v.union(v.number(), v.null()),
    priceTooCheapCents: v.union(v.number(), v.null()),
    priceCurrency: v.string(),
    closingExperience: v.optional(v.string()),
    completedPath: v.array(v.string()),
    userAgent: v.string(),
  }),
});
